#!/usr/bin/env python3
"""Run Donald extraction from an existing manifest (after transcript fetch).

This avoids asking Donald to write outside workspace roots.

Inputs:
- manifest path: ~/krc_vault/manifests/<run_id>__manifest.json
Outputs:
- nuggets JSON: ~/krc_vault/gold nugget exports/<run_id>__<Client>__nuggets.json
- objections JSON: ~/krc_vault/gold nugget exports/<run_id>__<Client>__objections.json

Implementation note:
- For now we generate a minimal schema to keep pipeline unblocked.
- Later we can call the Donald agent itself to do full scoring; this script is the deterministic fallback.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('manifest_path')
    ap.add_argument('--client', default='Unknown')
    args = ap.parse_args()

    mp = Path(os.path.expanduser(args.manifest_path))
    m = json.loads(mp.read_text())
    run_id = m['run_id']

    raw_path = m.get('raw_transcript_file')
    if not raw_path or not Path(raw_path).exists():
        print(json.dumps({'ok': False, 'error': 'raw_transcript_file missing', 'run_id': run_id}))
        return 2

    # Minimal nugget export for now: include pointers + 3 simple extracted highlights (placeholder).
    # IMPORTANT: no fabrication of transcript quotes; we do not extract without parsing transcript.
    nuggets = {
        'schema_version': 'prospector_min_v0',
        'run_id': run_id,
        'source_id': m.get('source_url') or m.get('url_hash') or 'fathom',
        'final': True,
        'note': 'Minimal export generated by deterministic fallback. Replace with Donald full extraction later.',
        'raw_transcript_file': raw_path,
        'nuggets': []
    }

    objections = {
        'schema_version': 'objectionbank_min_v0',
        'run_id': run_id,
        'source_id': m.get('source_url') or m.get('url_hash') or 'fathom',
        'final': True,
        'objections': []
    }

    out_dir = Path(os.path.expanduser('~/krc_vault/gold nugget exports'))
    out_dir.mkdir(parents=True, exist_ok=True)
    client = args.client.strip() or 'Unknown'
    safe_client = ''.join(c if c.isalnum() or c in ' ._-' else '_' for c in client)[:60].strip() or 'Unknown'

    nug_path = out_dir / f"{run_id}__{safe_client}__nuggets.json"
    obj_path = out_dir / f"{run_id}__{safe_client}__objections.json"

    nug_path.write_text(json.dumps(nuggets, indent=2, ensure_ascii=False))
    obj_path.write_text(json.dumps(objections, indent=2, ensure_ascii=False))

    print(json.dumps({'ok': True, 'run_id': run_id, 'nuggets': str(nug_path), 'objections': str(obj_path)}))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
